FROM postgres:18

ARG DEBIAN_FRONTEND="noninteractive"

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
RUN locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN apt-get update \
&& apt-get install -y --no-install-recommends postgresql-contrib-18 postgresql-plperl-18

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

COPY ./postgres/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
